[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer_runs = 1000000
via_ir = true
solc = "0.8.28"


remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/"
]